### ISSUE TITLE
Suggestion - add featured id to images

### ISSUE THREAD

**Issue by jzhu01** [ritsarassi/tea_cozy#1]
Seen here: https://github.com/ritsarassi/tea_cozy/blob/8821f4cba0ac0d15dc55afd05cf82433bdcf1b04/index.html#L37-L45

Currently, when the navigation is clicked it draws the user to the images of the Tea of the Month section with no description, so it might be useful to see what the images are for as well when directed there. 

See image: 
![screen shot 2018-04-24 at 5 05 21 pm](https://user-images.githubusercontent.com/15482346/39214234-cb3fbf9a-47e1-11e8-8978-795bf7672419.png)

**Comment by ritsarassi** [comment]
fixed
